// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnKirefQ9DQRsOFpjq2MJ8wLoaIBMzEM0',
    appId: '1:956782006207:web:11ccf54bf69bc7d4e4db0a',
    messagingSenderId: '956782006207',
    projectId: 'riodentdev',
    authDomain: 'riodentdev.firebaseapp.com',
    databaseURL: 'https://riodentdev-default-rtdb.firebaseio.com',
    storageBucket: 'riodentdev.firebasestorage.app',
    measurementId: 'G-3LL8QN84EQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA61dwkNYCn_b5sxOsfXYjcfeTb_gEcR3s',
    appId: '1:956782006207:android:cd1d7960a4c4700fe4db0a',
    messagingSenderId: '956782006207',
    projectId: 'riodentdev',
    databaseURL: 'https://riodentdev-default-rtdb.firebaseio.com',
    storageBucket: 'riodentdev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBQKk7hCMRYqrzBiyXrBFU7Tt6bKcwj5s',
    appId: '1:956782006207:ios:e70da532c650be80e4db0a',
    messagingSenderId: '956782006207',
    projectId: 'riodentdev',
    databaseURL: 'https://riodentdev-default-rtdb.firebaseio.com',
    storageBucket: 'riodentdev.firebasestorage.app',
    iosBundleId: 'com.riodent.riodent',
  );
}
