// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgyd6baF32BSwEXk92mCgbmMFoHAR123U',
    appId: '1:1085269643387:web:e518f7475e3abd791ad2de',
    messagingSenderId: '1085269643387',
    projectId: 'equip-services-dev',
    authDomain: 'equip-services-dev.firebaseapp.com',
    storageBucket: 'equip-services-dev.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6K45TORtk69fkeViGtdd6A6BQidhyNGg',
    appId: '1:1085269643387:android:57beff18a7a651941ad2de',
    messagingSenderId: '1085269643387',
    projectId: 'equip-services-dev',
    storageBucket: 'equip-services-dev.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBQKk7hCMRYqrzBiyXrBFU7Tt6bKcwj5s',
    appId: '1:956782006207:ios:e70da532c650be80e4db0a',
    messagingSenderId: '956782006207',
    projectId: 'riodentdev',
    databaseURL: 'https://riodentdev-default-rtdb.firebaseio.com',
    storageBucket: 'riodentdev.firebasestorage.app',
    iosBundleId: 'com.riodent.riodent',
  );
}
