import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

import 'app.dart';
import 'firebase_options.dart';

/// Application entry point.
///
/// Firebase is initialized using the configuration generated by FlutterFire CLI.
/// The environment is determined by --dart-define=ENV.
///
/// Usage:
///   flutter run                         → Development (riodentdev)
///   flutter run --dart-define=ENV=staging → Staging (future)
///   flutter run --dart-define=ENV=prod    → Production (future)
void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  runApp(
    const ProviderScope(
      child: RioDentApp(),
    ),
  );
}
